on:
  schedule:
  - cron: "0 4 * * *"
  push:
    branches:
    - main
    paths-ignore: # don't rebuild if only documentation has changed
    - "**.md"
env:
  ARCH: 'amd64'
  BUILDAH_ARGS: "--security-opt=label=disable --cap-add=all"
  IMAGE_NAME: rockylinux-base-experimental
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        VERSION:
        - '9'
    steps:
    - uses: actions/checkout@v4
    - name: Install Buildah
      shell: bash
      run: |
        sudo apt -y update
        sudo apt -y install buildah
    - name: Push bootc image
      shell: bash
      env:
        IMAGE: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_ID }}:${{ matrix.VERSION }}-${{ env.ARCH }}
        EXTRA_ARGS: --from=quay.io/rockylinux/rockylinux:${{ matrix.VERSION }} --build-arg=VARIANT=full --format oci --arch ${{ env.ARCH }} --security-opt=label=disable --cap-add=all
      run: |
        buildah login -u ${{ github.actor }} -p "${{ secrets.GITHUB_TOKEN }}"  ghcr.io
        buildah bud ${BUILDAH_ARGS} --no-cache -t ${IMAGE} ${EXTRA_ARGS}
        buildah push ${IMAGE}
        
