on:
  schedule:
  - cron: "0 4 * * *"
  push:
    branches:
    - main
    paths-ignore: # don't rebuild if only documentation has changed
    - "**.md"
env:
  ARCH: 'amd64'
  BUILDAH_ARGS: "--security-opt=label=disable --cap-add=all"
  IMAGE_NAME: rockylinux-base-experimental
jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        VERSION: 
        - '9'
    container:
      image: quay.io/buildah/stable:v1.34.0
    steps:
    - uses: actions/checkout@v4
    - name: Push bootc image
      shell: bash
      env:
        IMAGE_ID: ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:$VERSION-$ARCH
        IMAGE: $IMAGE_ID:$VERSION-$ARCH
        EXTRA_ARGS: --from=quay.io/rockylinux/rockylinux:$VERSION --build-arg=VARIANT=full --format oci --arch $ARCH --security-opt=label=disable --cap-add=all
      run: |
        buildah login ghcr.io -u ${{ github.actor }} --password "${{ secrets.GITHUB_TOKEN }}"
        buildah bud ${BUILDAH_ARGS} --no-cache -t ${IMAGE} ${EXTRA_ARGS}
        buildah push $IMAGE
        
